name: thea
description: "Thea, a theater booking system with integrated chatbot for youth and elderly."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.0
  printing: ^5.11.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.4
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  animated_icon: ^0.0.9
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/icons/
