name: thea
description: "Thea, a theater booking system with integrated chatbot for youth and elderly."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.0
  printing: ^5.11.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/
    - assets/icons/
